### ISSUE TITLE
2023 Upgrade

### ISSUE THREAD

**Issue by techenby** [andymnewhouse/iconi#4]
- [x] Upgrade to the latest version of Laravel
  - [x] Shift from v8 to v9 - #1 
  - [x] Shift mix to vite - #2 
  - [x] Shift from v9 to v10 - #3 
- [x] Add tighten/duster - #5 
- [x] Add GitHub actions - #6 
- [x] Update Readme to be useful #7
- [ ] Upgrade to Livewire v3
- [ ] Update Colors to latest Tailwind
